### ISSUE TITLE
[FEATURE] Add Before/After overlay with animations

### ISSUE THREAD

**Issue by kevinrutledge** [kevinrutledge/before-or-after#19]
## Description
Create an animated overlay that appears after a guess, showing "X is Before/After Y" to provide feedback on the correct relationship between cards. Implement smooth animations for overlay and card transitions.

## Steps to complete

1. Create `packages/react-frontend/src/components/ResultOverlay.jsx`:
   ```jsx
   /**
    * Display overlay with result of guess
    * @param {Object} props
    * @param {Boolean} props.visible - Whether overlay is visible
    * @param {String} props.oldTitle - Title of reference card
    * @param {String} props.newTitle - Title of compared card
    * @param {String} props.relation - "Before" or "After"
    * @param {Function} props.onAnimationComplete - Callback when animation finishes
    */
   ```

2. Add CSS for overlay and animations in `packages/react-frontend/src/App.css`:
   ```css
   .result-overlay {
     position: fixed;
     top: 0;
     left: 0;
     width: 100%;
     height: 100%;
     display: flex;
     justify-content: center;
     align-items: center;
     background-color: rgba(0, 0, 0, 0.7);
     z-index: 100;
     opacity: 0;
     transition: opacity 0.3s ease-in-out;
   }

   .result-overlay.visible {
     opacity: 1;
   }

   .result-message {
     font-size: 2rem;
     color: white;
     text-align: center;
     padding: 2rem;
     transform: scale(0.8);
     transition: transform 0.3s ease-in-out;
   }

   .result-overlay.visible .result-message {
     transform: scale(1);
   }
   ```

3. Implement card transition animations:
   ```css
   .card {
     transition: transform 0.5s ease-in-out;
   }

   .card-enter {
     transform: translateX(100%);
   }

   .card-enter-active {
     transform: translateX(0);
   }

   .card-exit {
     transform: translateX(0);
   }

   .card-exit-active {
     transform: translateX(-100%);
   }
   ```

4. Update `packages/react-frontend/src/pages/GamePage.jsx` to:
   - Import and use ResultOverlay component
   - Add state for overlay visibility
   - Set timeout to hide overlay after 1.5 seconds
   - Add classes for card animations based on game state

5. Create `packages/react-frontend/tests/components/ResultOverlay.test.jsx` to verify:
   - Overlay appears with correct message
   - Animation completes and triggers callback
   - Proper classes are applied during transitions

## Acceptance criteria

- After a guess, overlay appears with "[Old Title] is Before/After [New Title]".
- Overlay fades in smoothly and automatically disappears after 1.5 seconds.
- When a new card is drawn, it animates sliding in from the right.
- Old reference card slides out to the left when replaced.
- Animations work smoothly on both desktop and mobile devices.
- Component tests verify overlay behavior and animation classes.
- All transitions feel natural and enhance gameplay feedback.
