### ISSUE TITLE
[FEATURE] Build login page with localStorage token storage

### ISSUE THREAD

**Issue by kevinrutledge** [kevinrutledge/before-or-after#21]
## Description
Create a login page that captures user credentials, communicates with the auth endpoint, and stores the returned token in localStorage. Implement redirection to game page upon successful login.

## Steps to complete

1. Create `packages/react-frontend/src/pages/LoginPage.jsx`:
   ```jsx
   import { useState } from "react";
   import { useNavigate } from "react-router-dom";
   import Layout from "../components/Layout";
   import PageContainer from "../components/PageContainer";
   
   function LoginPage() {
     const [email, setEmail] = useState("");
     const [password, setPassword] = useState("");
     const [error, setError] = useState("");
     const [isLoading, setIsLoading] = useState(false);
     const navigate = useNavigate();
     
     async function handleSubmit(e) {
       e.preventDefault();
       setError("");
       setIsLoading(true);
       
       try {
         // Call login API
         const response = await fetch("/api/auth/login", {
           method: "POST",
           headers: { "Content-Type": "application/json" },
           body: JSON.stringify({ email, password })
         });
         
         if (!response.ok) {
           throw new Error("Login failed");
         }
         
         const data = await response.json();
         
         // Store token in localStorage
         localStorage.setItem("authToken", data.token);
         
         // Navigate to game page
         navigate("/game");
       } catch (err) {
         setError("Invalid email or password");
       } finally {
         setIsLoading(false);
       }
     }
     
     return (
       <Layout>
         <PageContainer>
           <div className="login-page">
             <h1>Login</h1>
             {error && <div className="error-message">{error}</div>}
             <form onSubmit={handleSubmit}>
               {/* Form fields */}
             </form>
           </div>
         </PageContainer>
       </Layout>
     );
   }
   
   export default LoginPage;
   ```

2. Add CSS styles in `packages/react-frontend/src/App.css`:
   ```css
   .login-page {
     max-width: 400px;
     margin: 0 auto;
     padding: 2rem;
     background-color: white;
     border-radius: 8px;
     box-shadow: var(--card-shadow);
   }
   
   .login-page h1 {
     text-align: center;
     margin-bottom: 1.5rem;
   }
   
   .form-group {
     margin-bottom: 1rem;
   }
   
   .form-group label {
     display: block;
     margin-bottom: 0.5rem;
     font-weight: bold;
   }
   
   .form-control {
     width: 100%;
     padding: 0.75rem;
     border: 1px solid #ddd;
     border-radius: 4px;
   }
   
   .login-button {
     width: 100%;
     padding: 0.75rem;
     background-color: var(--primary);
     color: white;
     border: none;
     border-radius: 4px;
     cursor: pointer;
   }
   
   .error-message {
     padding: 0.5rem;
     margin-bottom: 1rem;
     background-color: #fee;
     border: 1px solid #f88;
     border-radius: 4px;
     color: #c00;
   }
   ```

3. Update `packages/react-frontend/src/routes/Router.jsx` to add the login route:
   ```jsx
   import LoginPage from "../pages/LoginPage";
   
   // Inside Routes component
   <Route path="/login" element={<LoginPage />} />
   ```

4. Create utility for auth in `packages/react-frontend/src/utils/authUtils.js`:
   ```javascript
   /**
    * Check if user is authenticated
    * @returns {Boolean} True if auth token exists
    */
   export function isAuthenticated() {
     return localStorage.getItem("authToken") !== null;
   }
   
   /**
    * Get auth token for API requests
    * @returns {String|null} Auth token or null
    */
   export function getAuthToken() {
     return localStorage.getItem("authToken");
   }
   
   /**
    * Clear auth token (logout)
    */
   export function logout() {
     localStorage.removeItem("authToken");
   }
   ```

5. Create `packages/react-frontend/tests/pages/LoginPage.test.jsx` to verify:
   - Form renders correctly
   - Submission calls API with credentials
   - Success stores token and redirects
   - Errors display appropriately

## Acceptance criteria

- Login page displays form with email and password fields.
- Form validation prevents empty submissions.
- On successful login, token stores in localStorage.
- On successful login, user redirects to game page.
- Error messages display for failed login attempts.
- UI provides visual feedback during loading state.
- Form is responsive and accessible.
- Tests verify all login behaviors.
