### ISSUE TITLE
[CHORE] Configure theme with CSS variables in global.css

### ISSUE THREAD

**Issue by kevinrutledge** [kevinrutledge/before-or-after#24]
## Description
Modify existing global.css to implement a consistent theme using CSS variables based on RealTimeColors palette and Inter font. This provides a clean, polished design while maintaining simplicity for the MVP.

## Steps to complete

1. Update `packages/react-frontend/src/styles/global.css` to add theme variables:
   ```css
   /* Import Inter font */
   @import url('https://fonts.googleapis.com/css?family=Inter:700|Inter:400');

   /* Define root CSS variables */
   :root {
     /* Color scheme from RealTimeColors */
     --text: #100910;
     --background: #f9f5f9;
     --primary: #121212;
     --secondary: #E94F37;
     --accent: #2AB7CA;
     --card-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
   }

   /* Keep existing reset styles */
   * {
     margin: 0;
     padding: 0;
     box-sizing: border-box;
   }

   /* Update body font */
   body {
     font-family: 'Inter', sans-serif;
     line-height: 1.5;
     color: var(--text);
     background-color: var(--background);
   }

   h1, h2, h3, h4, h5 {
     font-family: 'Inter', sans-serif;
     font-weight: 700;
   }

   /* Rest of existing global.css with color references updated */
   ```

2. Update `packages/react-frontend/tailwind.config.js` to use the variables:
   ```javascript
   /** @type {import('tailwindcss').Config} */
   export default {
     content: [
       "./index.html",
       "./src/**/*.{js,jsx}"
     ],
     theme: {
       extend: {
         colors: {
           text: 'var(--text)',
           background: 'var(--background)',
           primary: 'var(--primary)',
           secondary: 'var(--secondary)',
           accent: 'var(--accent)',
         },
         boxShadow: {
           card: 'var(--card-shadow)',
         },
         fontFamily: {
           sans: ['Inter', 'sans-serif'],
         },
       },
     },
     plugins: [],
   }
   ```

3. Update color references in `packages/react-frontend/src/App.css`:
   ```css
   /* Replace hardcoded colors with variables */
   header h1 {
     color: var(--primary);
   }
   
   .start-button {
     background-color: var(--primary);
     color: white;
   }
   
   .lower-button {
     background-color: var(--secondary);
     color: white;
   }
   
   .higher-button {
     background-color: var(--accent);
     color: white;
   }
   
   /* Continue replacing other hardcoded colors */
   ```

## Acceptance criteria

- CSS variables define colors in global.css for central theme management
- Inter font loads and applies to all text elements
- Color scheme matches RealTimeColors palette
- Tailwind configuration extends theme with CSS variables
- Existing components use theme variables consistently
- No hardcoded colors remain in component styles
- Application maintains a clean, professional appearance
- No new files or components created to keep the MVP simple
- Project structure remains clean and minimal
